### ISSUE TITLE
Django version?

### ISSUE THREAD

**Issue by mitchb1** [divio/django-mailchimp#16]
With what django version is this compatible?

**Comment by davidrenne** [comment]
definitely not 1.7   

```
from django.utils import simplejson 
```

simplejson was taken out in 1.5 i think.  I will be looking at forks to find who has done good updates

**Comment by stevemac007** [comment]
Is there a preferred form, seeing as this has been broken for 2 years.

**Comment by czpython** [comment]
@stevemac007 hello, we've now taken over maintenance and the app is 1.6 compatible.
There's an outstanding pr for 1.7/1.8 compatibility.

I'll check with the pr author if he can land it this week so we can make a release.

**Comment by stevemac007** [comment]
Excellent, I'm running into this simplejson issue with 1.8, would be great if you can push a new release with this resolved.

**Comment by stevemac007** [comment]
@czpython how did the merge go? Looks like #50 was merged in, any chance of an updated release soon?

**Comment by czpython** [comment]
The supported django versions are now 1.6 to 1.8
