### ISSUE TITLE
MAILCHIMP_WEBHOOK_KEY warning?

### ISSUE THREAD

**Issue by deronsizemore** [divio/django-mailchimp#40]
Anytime I perform an activity in terminal I'm seeing the warning below. Is this something I should be concerned about?

MailchimpWarning: you did not define a MAILCHIMP_WEBHOOK_KEY setting. django-mailchimp will create a random one by itself
  "django-mailchimp will create a random one by itself", MailchimpWarning)

**Comment by hakanw** [comment]
+1

**Comment by bambamboole** [comment]
+1
I've got the same issue.
What has the MAILCHIMP_WEBHOOK_KEY to be?

**Comment by deronsizemore** [comment]
After more research on this, it's not a problem I don't think. It's just a warning anyway, but the warning is just saying you haven't specified a webhook_key from mailchimp. If you're not using webhooks, then there's really no reason to specify a key. Nothing to worry about.
