### ISSUE TITLE
Migrations break django 1.8

### ISSUE THREAD

**Issue by javiercf** [divio/django-mailchimp#51]
Migration files break Django 1.8 compatibility even when installing from git source, also a new release is pending following the changes to the simplejson import issue which broke compatibility starting Django 1.7

**Comment by czpython** [comment]
Hello @javiercf, Django 1.8 compatibility is being reviewed in pr #50.

**Comment by czpython** [comment]
Fixed by c4187f355923aa82bdb3fef21377167a136fc06f
