### ISSUE TITLE
Trouble with package, simplejson

### ISSUE THREAD

**Issue by Q-bart** [divio/django-mailchimp#52]
After installing, `manage.py runserver` cause error
`ImportError: cannot import name 'simplejson'`
It is because 
>django.utils.simplejson
>Since Django 1.5 drops support for Python 2.5, we can now rely on the json module being available in Python’s standard library, so we’ve removed our own copy of simplejson. You should now import json instead of django.utils.simplejson.

>Unfortunately, this change might have unwanted side-effects, because of incompatibilities between versions of simplejson – see the backwards-incompatible changes section. If you rely on features added to simplejson after it became Python’s json, you should import simplejson explicitly.

Please, fix it.

**Comment by Infernion** [comment]
+1

**Comment by Q-bart** [comment]
In what way? Latest commit was 24 days ago! I have opened this issue 14 days ago!...

**Comment by Infernion** [comment]
@Q-bart they fixed it before. But didn't update on pypi. 

I'm not sure need I use this package, because not Mailchimp switching to API v3, but here is v1.3, am I right?

**Comment by Q-bart** [comment]
seems so. I use official MailChimp python package

**Comment by j0hnsmith** [comment]
please release this change on pyi

**Comment by newearthmartin** [comment]
yes, please release it on pip

**Comment by codegastudio** [comment]
+1

**Comment by maltebeckmann** [comment]
I am getting:
  File "/home/.../lib/python3.4/site-packages/mailchimp/models.py", line 2, in <module>
    from django.utils import simplejson
ImportError: cannot import name 'simplejson'

Is this related?

**Comment by newearthmartin** [comment]
Yes, solution for me now is cloning the repo into your project instead of
using pip.

**Comment by danigosa** [comment]
Release it for God Sake! +10000

**Comment by zruu** [comment]
I agree. We need to update this.

**Comment by czpython** [comment]
Fixed in 1.4.0
