### ISSUE TITLE
Plain text "confirm subscription" email?

### ISSUE THREAD

**Issue by deronsizemore** [divio/django-mailchimp#53]
I have the option for double opt in set to true and all users who sign up will receive an email asking them to confirm their subscription. This email comes across in plain text rather than the standard nicely designed html email that mailchimp allows you to set up. I'm not sure if this is a problem with Django mailchimp or mailchimp? And ideas?

**Comment by Infernion** [comment]
I have same. When subscribe throw mailchimp form message is nice, when throw django-mailchimp it's plain text

**Comment by deronsizemore** [comment]
I meant to update this ticket but forgot. I figured it out. The django-mailchimp sets it as text by default it looks like. Here's what I'm doing to send HTML:

    list.subscribe(user.email, {'EMAIL': user.email}, double_optin=True, email_type='html')
