### ISSUE TITLE
ImportError raised when trying to load mailchimp.templatetags.mailchimp_tags

### ISSUE THREAD

**Issue by maj0rr** [divio/django-mailchimp#69]
Hey,

I'm getting this error when I add 'mailchimp' to my INSTALLED_APPS

`django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'mailchimp.templatetags.mailchimp_tags': cannot import name BaseView`

Requirements:
Django==1.11
django-mailchimp-v1.3==1.4
Python 2.7.6

Any Ideas?

Thanks

**Comment by aperechnev** [comment]
So what is the solution?

**Comment by maj0rr** [comment]
Hey @aperechnev,

adding the 'mailchimp' to the top of my INSTALLED_APPS solved the issue for me.

`
INSTALLED_APPS = (
    'mailchimp',
    ...
)
`
